language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"

install: source build_tools/travis/install.sh

script:
  - if [ ${COVERAGE} == "true" ];
    then pytest --cov=skopt --durations=10; else
    pytest --durations=10;
    fi

after_success:
  - if [ ${COVERAGE} == "true" ]; then
    pip install codecov;
    codecov;
    fi
